init:
  - git config --global core.autocrlf true
image: Visual Studio 2017
build: off
platform: x64
shallow_clone: true
skip_tags: true

environment:
  PHP_VERSION: 7.2.0
  NODE_VERSION: 8

install:
  - ps: Install-Product node $env:NODE_VERSION
  - cinst php -y --version %PHP_VERSION%
  - SET PATH=C:\tools\php72;%PATH%
  - C:\ProgramData\chocolatey\bin\RefreshEnv
  - npm install -g yarn
  - cd %APPVEYOR_BUILD_FOLDER%
  - yarn install

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm test

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json
